// Builds the data behind the /reliability page from recorded eval runs and the document generator. Nothing here
// calls the model: every conclusion, score and range shown on that page is read from evals/*/results.
//   npx tsx scripts/reliability-data.ts --write   regenerate src/fixtures/reliability.json
//   npx tsx scripts/reliability-data.ts           check the committed fixture still matches the recorded runs (npm test)
import fs from "node:fs";
import path from "node:path";
import { buildDocs, ROOMS } from "./docs/itc-transfer";

const root = process.cwd();
const OUT = path.join(root, "src/fixtures/reliability.json");

// The recorded runs the page is built from. Each is a live run of the full pipeline, saved by scripts/eval.ts.
const RUNS = {
  cottonwood: "evals/itc-transfer/results/2026-10-07T06-23-26-768Z.json", // the run the replay fixture was made from
  cleanFirst: "evals/itc-transfer-clean/results/2026-10-07T06-15-53-633Z.json", // first clean-room run: the failure
  cleanAfter: "evals/itc-transfer-clean/results/2026-10-07T06-26-13-251Z.json", // after the general rule fix
  perturbed: "evals/itc-transfer-perturbed/results/2026-10-07T06-29-08-014Z.json",
} as const;

type Row = { check: string; pass: boolean; detail: string };
interface Quote { docId: string; page: number; text: string; verified: boolean }
interface EvidenceRec { assumptionId: string; docId: string; note: string; stance: string; quote: Quote }
interface FindingRec { assumptionId: string; label: string; currentDisplay: string; summary: string }
interface Saved {
  model: string;
  room: string;
  results: {
    rows: Row[];
    quoteRate: number;
    quotes: number;
    seconds: number;
    usage: { costUsd: number };
    run: { ev: { evidence: EvidenceRec[] }; rc: { findings: FindingRec[]; questions: { prompt: string }[]; rfis: unknown[]; risks: { title: string; detail: string }[] } };
  }[];
}

const load = (rel: string): Saved => JSON.parse(fs.readFileSync(path.join(root, rel), "utf8"));
const stampOf = (rel: string) => path.basename(rel, ".json").replace(/T(\d\d)-(\d\d)-(\d\d)-\d+Z$/, "T$1:$2:$3Z");

function summary(rel: string) {
  const s = load(rel);
  const r = s.results[0];
  const rangeRow = (end: "low" | "high") => {
    const row = r.rows.find((x) => x.check.startsWith(`range ${end} `))!;
    return { expected: Number(row.check.split(" ")[2]), got: Number(row.detail), pass: row.pass };
  };
  const finding = (id: string) => {
    const f = r.run.rc.findings.find((x) => x.assumptionId === id)!;
    return { label: f.label, display: f.currentDisplay, summary: f.summary };
  };
  return {
    file: rel,
    room: s.room,
    stamp: stampOf(rel),
    model: s.model,
    checks: r.rows.length,
    passed: r.rows.filter((x) => x.pass).length,
    quotes: r.quotes,
    quotesVerified: Math.round(r.quotes * r.quoteRate),
    costUsd: Math.round(r.usage.costUsd * 100) / 100,
    seconds: Math.round(r.seconds),
    failedRows: r.rows.filter((x) => !x.pass),
    // The construction-start check and the two checks that hang on it.
    rows: r.rows.filter((x) => /^(label|question|no question for) T[568]\b|^questions |^range /.test(x.check)),
    findings: { T6: finding("T6"), T5: finding("T5"), T8: finding("T8") },
    // What the model wrote about the independent engineer's report while weighing the construction start.
    ieNotes: r.run.ev.evidence.filter((e) => e.assumptionId === "T6" && e.docId === "D05").map((e) => ({ note: e.note, quote: e.quote.text, verified: e.quote.verified })),
    questions: r.run.rc.questions.map((q) => q.prompt),
    rfis: r.run.rc.rfis.length,
    risks: r.run.rc.risks.map((k) => ({ title: k.title, detail: k.detail })),
    range: { low: rangeRow("low"), high: rangeRow("high") },
  };
}

/** The independent engineer's construction-history paragraphs in one room, exactly as generated into its PDF. */
function ieReport(room: keyof typeof ROOMS) {
  const d05 = buildDocs(ROOMS[room]).find((d) => d.id === "D05")!;
  const start = d05.blocks.findIndex((b) => typeof b === "object" && "h" in b && /Construction History/.test(b.h));
  const paragraphs: string[] = [];
  for (const b of d05.blocks.slice(start + 1)) {
    if (typeof b !== "string") break;
    paragraphs.push(b);
  }
  // The sentence that differs between rooms: whether the engineer reviewed the manufacturer's records.
  const key = paragraphs.join(" ").split(/(?<=\.)\s+/).find((s) => /reviewed the manufacturer/.test(s))!;
  return { pdf: `/demo-data/${room}/${d05.filename}`, title: d05.title, paragraphs, key };
}

export function buildReliability() {
  return {
    note: "Generated by scripts/reliability-data.ts from recorded eval runs; do not edit by hand.",
    runs: {
      cottonwood: summary(RUNS.cottonwood),
      cleanFirst: summary(RUNS.cleanFirst),
      cleanAfter: summary(RUNS.cleanAfter),
      perturbed: summary(RUNS.perturbed),
    },
    ie: { cottonwood: ieReport("itc-transfer"), clean: ieReport("itc-transfer-clean"), perturbed: ieReport("itc-transfer-perturbed") },
  };
}

const fresh = JSON.stringify(buildReliability(), null, 2) + "\n";
if (process.argv.includes("--write")) {
  fs.writeFileSync(OUT, fresh);
  console.log("wrote", path.relative(root, OUT));
} else {
  const committed = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : "";
  if (committed !== fresh) {
    console.error("FAIL src/fixtures/reliability.json does not match the recorded runs; run: npx tsx scripts/reliability-data.ts --write");
    process.exit(1);
  }
  console.log("PASS reliability page data matches the recorded eval runs");
}
